# Generated by Django 5.2.5 on 2025-08-19 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopenings',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='jobopenings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobopenings',
            name='posted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobopenings',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
